version: '2'
services:
    jhipsterpress-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipsterpress/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterpress
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
